### PR TITLE
Fix 64 Byte Password bug for structures that don't support .push (Fixes Issue #11)

### LINKED ISSUE #11: [Bug] Error when input password more than 64byte
How to reproduce:
1. Open the page: http://ricmoo.github.io/scrypt-js/
2. Input password more than 64 bytes.
3. Click "Compute scrypt"

This make a error:
```
scrypt.js:90 Uncaught TypeError: p.push is not a function
    at SHA256 (scrypt.js:90)
    at PBKDF2_HMAC_SHA256_OneIter (scrypt.js:117)
    at scrypt (scrypt.js:285)
    at HTMLInputElement.submit.onclick ((index):254)
```

```scrypt``` function passes the password to  ```PBKDF2_HMAC_SHA256_OneIter``` function,
When password is more than 64bytes,  ```PBKDF2_HMAC_SHA256_OneIter``` function run ```SHA256``` for password.
```SHA256``` expects that the argument is Array but user uses ```Buffer```.

I think  ```PBKDF2_HMAC_SHA256_OneIter``` should convert password to Array or ```scrypt``` should only support Array.

### PR DESCRIPTION
**Pull request by TotalTechGeek**
This is a PR to fix #11

I've also submitted patches to scrypt-async-js

### CODE REVIEW

**Comment by TotalTechGeek** [comment]
@ricmoo This patch was merged into [scrypt-async-js](https://github.com/dchest/scrypt-async-js/pull/43) and [scrypt-async-modern](https://github.com/Cretezy/scrypt-async-modern/pull/1).

The bug was unfortunately propagated across multiple projects.

**Comment by ricmoo** [comment]
Have you found official test vectors for this?

I can install the official C reference solution to generate some test cases, but certainly want to make sure this matches the official implementation.

I will work on this today.

**Comment by TotalTechGeek** [comment]
As far as I am aware, there are not official test vectors on scrypt's end for keys longer than the block-size. 

The test vector that I added does match a few of the implementations I've tested against (including the scrypt function supported in Node.js 10)

image

A few more test cases may need to be generated against the official implementation.

**Comment by ricmoo** [comment]
Fixed in `scrypt-js@2.0.4`.

Let me know if you still have any issues.

Thanks! :)

**Comment by ricmoo** [comment]
(test cases were generated by adding them to the reference implementation in `test/test_scrypt.c`)

**Pull request closed without merging**
